# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Set environment variables
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_NAME=products
ENV DB_USERNAME=user_products
ENV DB_PASSWORD=password

# Copy the Gradle wrapper and build files from the ms_products directory
COPY ../gradlew .
COPY ../gradle gradle
COPY ../build.gradle .
COPY ../settings.gradle .

# Copy the source code from the ms_products directory
COPY ../src src

# Grant execution rights to the Gradle wrapper
RUN chmod +x gradlew

# Build the application
RUN ./gradlew build

# Expose the port the application runs on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "build/libs/ms_products-0.0.1-SNAPSHOT.jar"]